### ISSUE TITLE
unable to train model

### ISSUE THREAD

**Issue by jaburges** [st0nedB/rooms#7]
**Describe the bug**
```
WARNING:root:scikit-learn version 0.24.0 is not supported. Minimum required version: 0.17. Maximum required version: 0.19.2. Disabling scikit-learn conversion API.
WARNING:root:TensorFlow version 1.15.2 detected. Last version known to be fully compatible is 1.15.0 .
Traceback (most recent call last):
  File "roomsModelMaker.py", line 179, in <module>
    X, Y = parseData(jsondata=data, rooms=rooms, nsamples=nsamples, lb=lbinarizer)
  File "roomsModelMaker.py", line 84, in parseData
    data[ii:ii+N] = dd
ValueError: could not broadcast input array from shape (120,2) into shape (120,7)
```
**To Reproduce**
Folder has the various rooms .json files in
pipenv working with dependencies listed

**Comment by jaburges** [comment]
using Python 3.7
tensorflow 1.15.0 
I get the following (mostly warnings) but scikit-learn wont install for some reason?
```
jaburges@UbuntuServer:~/rooms/machine-learning-python$ pipenv install
Creating a virtualenv for this project...
Pipfile: /home/jaburges/rooms/machine-learning-python/Pipfile
Using /usr/bin/python3.7m (3.7.9) to create virtualenv...
⠸ Creating virtual environment...created virtual environment CPython3.7.9.final.0-64 in 166ms
  creator CPython3Posix(dest=/home/jaburges/.local/share/virtualenvs/machine-learning-python-aQW9Fdoj, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/home/jaburges/.local/share/virtualenv)
    added seed packages: pip==20.3.1, setuptools==51.0.0, wheel==0.36.1
  activators BashActivator,CShellActivator,FishActivator,PowerShellActivator,PythonActivator,XonshActivator
✔ Successfully created virtual environment!
Virtualenv location: /home/jaburges/.local/share/virtualenvs/machine-learning-python-aQW9Fdoj
Installing dependencies from Pipfile.lock (356100)...
  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 101/101 — 00:02:22
To activate this project's virtualenv, run pipenv shell.
Alternatively, run a command inside the virtualenv with pipenv run.
jaburges@UbuntuServer:~/rooms/machine-learning-python$ pipenv shell
Launching subshell in virtual environment...
jaburges@UbuntuServer:~/rooms/machine-learning-python$  . /home/jaburges/.local/share/virtualenvs/machine-learning-python-aQW9Fdoj/bin/activate
(machine-learning-python) jaburges@UbuntuServer:~/rooms/machine-learning-python$ python3.7 roomsModelMaker.py --num-beacon 7
/home/jaburges/.local/share/virtualenvs/machine-learning-python-aQW9Fdoj/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/jaburges/.local/share/virtualenvs/machine-learning-python-aQW9Fdoj/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/jaburges/.local/share/virtualenvs/machine-learning-python-aQW9Fdoj/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/jaburges/.local/share/virtualenvs/machine-learning-python-aQW9Fdoj/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:519: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/home/jaburges/.local/share/virtualenvs/machine-learning-python-aQW9Fdoj/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:520: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/home/jaburges/.local/share/virtualenvs/machine-learning-python-aQW9Fdoj/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
/home/jaburges/.local/share/virtualenvs/machine-learning-python-aQW9Fdoj/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:541: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/jaburges/.local/share/virtualenvs/machine-learning-python-aQW9Fdoj/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:542: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/jaburges/.local/share/virtualenvs/machine-learning-python-aQW9Fdoj/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:543: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/jaburges/.local/share/virtualenvs/machine-learning-python-aQW9Fdoj/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:544: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/home/jaburges/.local/share/virtualenvs/machine-learning-python-aQW9Fdoj/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:545: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/home/jaburges/.local/share/virtualenvs/machine-learning-python-aQW9Fdoj/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:550: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
Traceback (most recent call last):
  File "roomsModelMaker.py", line 19, in <module>
    from sklearn.metrics import plot_confusion_matrix, confusion_matrix, ConfusionMatrixDisplay
ImportError: cannot import name 'plot_confusion_matrix' from 'sklearn.metrics' (/home/jaburges/.local/share/virtualenvs/machine-learning-python-aQW9Fdoj/lib/python3.7/site-packages/sklearn/metrics/__init__.py)
```

**Comment by jaburges** [comment]
so scikit-learn==0.23.0 fails another dependency test:
`WARNING:root:scikit-learn version 0.23.2 is not supported. Minimum required version: 0.17. Maximum required version: 0.19.2. Disabling scikit-learn conversion API`

so results in:
```
Traceback (most recent call last):
  File "roomsModelMaker.py", line 175, in <module>
    X, Y = parseData(jsondata=data, rooms=rooms, nsamples=nsamples, lb=lbinarizer)
  File "roomsModelMaker.py", line 84, in parseData
    data[ii:ii+N] = dd
ValueError: could not broadcast input array from shape (120,2) into shape (120,7)
```

and scikit-learn==0.19.2 results the message above

**Comment by st0nedB** [comment]
With the files you have send me for inspection, it seems that the issue is either a misconfiguration in the beacon section of the app, or some weird error in the programming. The files only contain measurements from two beacons. Hence, the training fails when you specify to train for seven beacons. 
Data collection must only be started after all beacons have been entered. The app only scans for those beacons configured in the settings.
I suggest you checkout the latest version, rebuild, check your app config and re-collect a small amount of data (i.e. for a single area) and check the exported `*.json` files with your favorite editor. The arrays should contain single vectors, each with as many elements as configured beacons. Please report back, if the issue persists.

**Comment by jaburges** [comment]
ok, thanks for the response - will give that a go

**Comment by jaburges** [comment]
hmmm - ok the app crashes when trying to train an existing room.
removing the room didnt solve the issue.
Will remove and re-add the app 

Interestingly you are right, the room shows "2 Beacons" but during the training was showing 6 or 7 beacons visible.

**Comment by st0nedB** [comment]
Ok, sounds weird. If all beacons are configured correctly, the device will log a value for each beacon, regardless whether it receives a signal or not (as knowing something is not there is also valuable information).
Please let me know, whether it works after the reinstall.

**Comment by jaburges** [comment]
havent narrowed down the issue, but if there is an issue training the app crashes, and need to re-install it to try again.

**Comment by jaburges** [comment]
So I can confirm this time during training the app could see 5 beacons (if you need i took a screenshot)

However on looking at the data, it only shows 2 beacons again.

**Comment by st0nedB** [comment]
Ok, this makes me wonder. Please check the following:
- all beacons must have the __same__ UUID
- all beacons must have the __same__ major ID
- each beacon must have a __different__ minor ID

Only in this configuration the app will work as expected.

**Comment by st0nedB** [comment]
Closing this due to inactivity.
